name: Build Bento4 Android Static Libs

on: [workflow_dispatch]

env:
  NDK_VERSION: r26d
  CMAKE_VERSION: 3.22.1

jobs:
  build-android:
    runs-on: ubuntu-22.04
    
    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # Set up Android NDK
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: ${{ env.NDK_VERSION }}
        add-to-path: true
        
    # Install dependencies
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        wget -q https://github.com/Kitware/CMake/releases/download/v${{ env.CMAKE_VERSION }}/cmake-${{ env.CMAKE_VERSION }}-linux-x86_64.sh
        chmod +x cmake-${{ env.CMAKE_VERSION }}-linux-x86_64.sh
        sudo ./cmake-${{ env.CMAKE_VERSION }}-linux-x86_64.sh --skip-license --prefix=/usr/local
        
    # Clone Bento4
    - name: Clone Bento4
      run: |
        git clone --recurse-submodules https://github.com/axiomatic-systems/Bento4.git
        cd Bento4
        git checkout v1.6.0-641
        
    # Build for Android architectures
    - name: Build Bento4 Static Libs
      working-directory: Bento4
      run: |
        mkdir -p build-android
        cd build-android
        
        ARCHS=("armeabi-v7a" "arm64-v8a" "x86" "x86_64")
        API_LEVEL=24
        
        for ARCH in "${ARCHS[@]}"; do
          echo "Building for $ARCH"
          mkdir -p $ARCH
          cd $ARCH
          
          cmake \
            -DCMAKE_TOOLCHAIN_FILE=${{ env.ANDROID_NDK_HOME }}/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=$ARCH \
            -DANDROID_PLATFORM=android-${API_LEVEL} \
            -DANDROID_STL=c++_static \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja \
            -G Ninja \
            ../..
            
          ninja -j$(nproc)
          cd ..
        done
        
    # Prepare artifacts
    - name: Prepare artifacts
      run: |
        mkdir -p artifacts
        cd Bento4/build-android
        for ARCH in armeabi-v7a arm64-v8a x86 x86_64; do
          mkdir -p ../../artifacts/$ARCH/lib
          mkdir -p ../../artifacts/$ARCH/include
          cp $ARCH/lib/*.a ../../artifacts/$ARCH/lib/
          cp -r ../../Source/C++/Headers/* ../../artifacts/$ARCH/include/
        done
        
    # Upload artifacts
    - name: Upload Android Static Libs
      uses: actions/upload-artifact@v4
      with:
        name: bento4-android-static-libs-${{ github.sha }}
        path: artifacts/
        retention-days: 30
        compression-level: 6
